name: 'Comment usage instructions on PRs'
description: 'Comment usage instructions on PRs'

inputs:
  tag:
    description: "Image tag to pull"
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate config
      id: ev
      uses: ./.github/actions/docker-push-variables
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: bento PR Installation instructions
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          bento PR Installation instructions

          Your PR has been built and pushed to the following image tag:

          ```
          ghcr.io/bentodevs/bento-app:${{ inputs.tag }}
          ```
        edit-mode: replace