name: Code Review Automation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
         reporter: github-pr-review
         eslint_flags: 'src/'