name: reviewdog
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-review # Change reporter.
          eslint_flags: 'src/'