name: Run ESLint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        run : |
          npm ci
      - name: Run ESLint
        run: |
          npm run lint