name: Create Sentry Release

on:
  release:

jobs:
  sentry:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: lasalefamine/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
        with:
          environment: production
          version: ${{ github.ref }}
          version_prefix: "v"