name: Check Typescript compile state
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile-ts:
   name: Check compile readiness
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Node v16
      uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Install packages
      run: npm install
    - name: Compile application
      run: tsc
